# application.yml
server:
  port: 18081
spring:
  application:
    name: goods
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/market_goods?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
      instance:
        prefer-ip-address: true
    enabled: true

